# Podstawowa konfiguracja strony
title: OpenIT.pro - Profesjonalne usługi IT
email: kontakt@openit.pro
description: >- 
  Profesjonalne usługi IT dla firm, instytucji i szkół. 
  Kompleksowa obsługa informatyczna, bezpieczeństwo danych 
  i wsparcie techniczne.
baseurl: ""
url: "https://mkieszek.github.io" # URL dla GitHub Pages
source: "."

# Ustawienia SEO
lang: pl-PL
author: OpenIT.pro
twitter:
  username: openitpro
  card: summary_large_image
logo: /assets/images/logo.png

# Ustawienia budowania
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-theme-hacker

# Ustawienia motywu
title-heading: false  # wyłącza domyślny nagłówek motywu
show-downloads: false # wyłącza przyciski pobierania
google_analytics: false # wyłącza GA

# Ustawienia Sass
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
    - /usr/local/bundle/gems/jekyll-theme-hacker-0.2.0/_sass
  sass_dir: _sass
  load_paths:
    - _sass
    - /usr/local/bundle/gems/jekyll-theme-hacker-0.2.0/_sass

# Wyłączenie plików z budowania
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md

# Kolekcje
collections:
  case-studies:
    output: true
    permalink: /case-studies/:path/
    sort_by: title

# Domyślne wartości dla stron
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "case-studies"
    values:
      layout: case-study
  - scope:
      path: "_case-studies"
    values:
      layout: case-study
